### PR TITLE
feat: Add functionality for using Prisma as a query builder

### PR DESCRIPTION
**Pull request by LucianBuzzo**
Ability expressions can now be defined using a function, that returns
either a Prisma "where" clause as an object, or a Prisma client
`findFirst` or `findUnique` query. Context or row values can be
interpolated using the `row` and `context` arguments passed to the
function.

```ts
const userAbilities = {
  Post: {
    insertOwnPost: {
        description: "Insert own post",
        // You can express the rule as a Prisma `where` clause.
        expression: (client, row, context) => {
          return {
            // This expression uses a context setting returned by the getContext function
            authorId: context('user.id')
          }
        },
        operation: "INSERT",
    },
  },
  Comment: {
      deleteOnOwnPost: {
          description: "Delete comment on own post",
          // You can also express the rule as a conventional Prisma query.
          expression: (client, row, context) => {
            return client.post.findFirst({
              where: {
                id: row('postId'),
                authorId: context('user.id')
              }
            })
          },
          operation: "DELETE",
      },
  }
}
```

Signed-off-by: Lucian Buzzo <lucian.buzzo@gmail.com>

### CODE REVIEW

**Comment by SarjuHansaliya** [comment]
sure @LucianBuzzo

**Comment by LucianBuzzo** [comment]
@SarjuHansaliya Have you had a chance to look at this yet?

**Review by SarjuHansaliya — CHANGES_REQUESTED** [review]
@LucianBuzzo this looks good to me, awesome work 🚀 
I see Publish check is failing, was that expected ?

**Comment by LucianBuzzo** [comment]
@SarjuHansaliya Yep It's expected as the cerebrum token we are using is not available on public repos. I have a ticket to resolve the issue.

**Comment by LucianBuzzo** [comment]
@SarjuHansaliya GitHub says that you requested changes, but I don't see what they are. Is it a mistake?

**Comment by SarjuHansaliya** [comment]
yes let me approve PR

**Review by SarjuHansaliya — APPROVED** [review]

**Pull request merged**
